[bridge.default_check_interval]
# cbridge events
send = 2
relay = 2
liquidity_added = 2
withdraw_done = 3
signers_updated = 2
# pegbridge events
deposited = 2
mint = 3
burn = 2
withdrawn = 3
# eth events
delegation_update = 20

[[multichain]]
chainID = 1
name = "Ethereum mainnet"
# Private gateway endpoint recommended
gateway = "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
blkinterval = 15
blkdelay = 8
forwardblkdelay = 5
cbridge = "0x5427FEFA711Eff984124bFBB1AB6fbf5E3DA1820"
otvault = "0xB37D31b2A74029B5951a2778F959282E2D518595"
ptbridge = "0x16365b45EB269B5B5dACB34B4a15399Ec79b95eB"
addgasestimateratio = 0.6

[[multichain]]
chainID = 56
name = "BSC"
# Private gateway endpoint recommended
gateway = "https://bsc-dataseed.binance.org"
blkinterval = 15
blkdelay = 20
forwardblkdelay = 50
maxblkdelta = 5000
cbridge = "0xdd90E5E87A2081Dcf0391920868eBc2FFB81a1aF"
otvault = "0x78bc5Ee9F11d133A08b331C2e18fE81BE0Ed02DC"
ptbridge = "0xd443FE6bf23A4C9B78312391A30ff881a097580E"
addgasgwei = 2
addgasestimateratio = 0.3

[[multichain]]
chainID = 42161
name = "Arbitrum"
# Private gateway endpoint recommended
gateway = "https://arb1.arbitrum.io/rpc"
blkinterval = 10
blkdelay = 1
forwardblkdelay = 500
maxblkdelta = 99999
cbridge = "0x1619DE6B6B20eD217a58d00f37B9d47C7663feca"
otvault = "0xFe31bFc4f7C9b69246a6dc0087D91a91Cb040f76"
ptbridge = "0xbdd2739AE69A054895Be33A22b2D2ed71a1DE778"
addgasestimateratio = 0.3

[[multichain]]
chainID = 137
name = "Polygon"
# Private gateway endpoint recommended
gateway = "https://polygon-rpc.com"
blkinterval = 15
blkdelay = 80
forwardblkdelay = 50
maxblkdelta = 5000
cbridge = "0x88DCDC47D2f83a99CF0000FDF667A468bB958a78"
otvault = "0xc1a2D967DfAa6A10f3461bc21864C23C1DD51EeA"
ptbridge = "0x4d58FDC7d0Ee9b674F49a0ADE11F26C3c9426F7A"
addgasestimateratio = 0.3

[[multichain]]
chainID = 43114
name = "Avalanche"
gateway = "https://api.avax.network/ext/bc/C/rpc"
blkinterval = 15
blkdelay = 15
forwardblkdelay = 50
cbridge = "0xef3c714c9425a8F3697A9C969Dc1af30ba82e5d4"
otvault = "0x5427FEFA711Eff984124bFBB1AB6fbf5E3DA1820"
ptbridge = "0x88DCDC47D2f83a99CF0000FDF667A468bB958a78"
addgasestimateratio = 0.3

[[multichain]]
chainID = 250
name = "Fantom"
# Private gateway endpoint recommended
gateway = "https://rpc.ftm.tools"
blkinterval = 10
blkdelay = 30
maxblkdelta = 10000
forwardblkdelay = 80
cbridge = "0x374B8a9f3eC5eB2D97ECA84Ea27aCa45aa1C57EF"
otvault = "0x7D91603E79EA89149BAf73C9038c51669D8F03E9"
ptbridge = "0x38D1e20B0039bFBEEf4096be00175227F8939E51"
addgasgwei = 2
addgasestimateratio = 0.3

[[multichain]]
chainID = 10
name = "Optimism"
# Private gateway endpoint recommended
gateway = "https://mainnet.optimism.io"
blkinterval = 10
blkdelay = 1
forwardblkdelay = 50
maxblkdelta = 10000
cbridge = "0x9D39Fc627A6d9d9F8C831c16995b209548cc3401"
ptbridge = "0x61f85fF2a2f4289Be4bb9B72Fc7010B3142B5f41"
addgasestimateratio = 0.3

[[multichain]]
chainID = 288
name = "Boba"
gateway = "https://mainnet.boba.network/"
blkinterval = 10
blkdelay = 1
forwardblkdelay = 500
maxblkdelta = 10000
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
otvault = "0x8db213bE5268a2b8B78Af08468ff1EA422073Da0"
ptbridge = "0xC5Ef662b833De914B9bA7a3532C6BB008a9b23a6"
addgasestimateratio = 0.3

[[multichain]]
chainID = 1666600000
name = "Harmony"
gateway = "https://harmony-0-rpc.gateway.pokt.network"
blkinterval = 10
blkdelay = 15
forwardblkdelay = 500
maxblkdelta = 1024
cbridge = "0x78a21c1d3ed53a82d4247b9ee5bf001f4620ceec"
ptbridge = "0xdd90e5e87a2081dcf0391920868ebc2ffb81a1af"
addgasestimateratio = 0.3
proxyport = 10300

[[multichain]]
chainID = 42220
name = "Celo"
gateway = "https://forno.celo.org"
blkinterval = 10
blkdelay = 10
forwardblkdelay = 100
maxblkdelta = 10000
cbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
otvault = "0xD9d1034ef3d21221F008C7e96346CA999966752C"
ptbridge = "0xDA1DD66924B0470501aC7736372d4171cDd1162E"
addgasestimateratio = 0.3
proxyport = 10301

[[multichain]]
chainID = 1088
name = "Metis Andromeda Mainnet"
gateway = "https://andromeda.metis.io/?owner=1088"
blkinterval = 15
blkdelay = 1
forwardblkdelay = 50
maxblkdelta = 10000
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
ptbridge = "0x3bbaDFf9aeee4a74D3Cf6da05C30868C9Ff85BB8"
addgasestimateratio = 0.3

[[multichain]]
chainID = 1313161554
name = "Aurora MainNet"
gateway = "https://mainnet.aurora.dev"
blkinterval = 15
blkdelay = 30
forwardblkdelay = 200
maxblkdelta = 10000
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
ptbridge = "0x4384d5a9D7354C65cE3aee411337bd40493Ad1bC"
addgasestimateratio = 0.3

[[multichain]]
chainID = 1285
name = "Moonriver"
gateway = "https://rpc.api.moonriver.moonbeam.network"
blkinterval = 20
blkdelay = 6
forwardblkdelay = 200
maxblkdelta = 10000
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
ptbridge = "0x374B8a9f3eC5eB2D97ECA84Ea27aCa45aa1C57EF"
addgasestimateratio = 0.3
proxyport = 10302

[[multichain]]
chainID = 100
name = "xDai"
gateway = "https://rpc.gnosischain.com/oe-only"
blkinterval = 15
blkdelay = 10
forwardblkdelay = 200
maxblkdelta = 10000
cbridge = "0x3795C36e7D12A8c252A20C5a7B455f7c57b60283"
ptbridge = "0xd4c058380D268d85bC7c758072f561e8f2dB5975"
addgasestimateratio = 0.3

[[multichain]]
chainID = 66
name = "OEC"
gateway = "https://exchainrpc.okex.org"
blkinterval = 15
blkdelay = 10
forwardblkdelay = 200
maxblkdelta = 2000
cbridge = "0x6a2d262D56735DbA19Dd70682B39F6bE9a931D98"
ptbridge = "0x48284Eb583a1F3058F4BCe0a685D44FE29d4539e"
addgasestimateratio = 0.3

[[multichain]]
chainID = 128
name = "Heco"
gateway = "https://http-mainnet-node.huobichain.com"
blkinterval = 15
blkdelay = 12
forwardblkdelay = 200
maxblkdelta = 5000
cbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
ptbridge = "0x81ECac0D6Be0550A00FF064a4f9dd2400585FE9c"
addgasestimateratio = 0.3

[[multichain]]
chainID = 42262
name = "OASIS"
gateway = "https://emerald.oasis.dev"
blkinterval = 30
blkdelay = 8
forwardblkdelay = 50
maxblkdelta = 100
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
ptbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
addgasestimateratio = 0.3

[[multichain]]
chainID = 1284
name = "Moonbeam"
gateway = "https://rpc.api.moonbeam.network"
blkinterval = 20
blkdelay = 6
forwardblkdelay = 200
maxblkdelta = 10000
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
ptbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
addgasestimateratio = 0.3
proxyport = 10303

[[multichain]]
chainID = 592
name = "Astar"
gateway = "https://rpc.astar.bldnodes.org/"
blkinterval = 30
blkdelay = 6
forwardblkdelay = 200
maxblkdelta = 10000
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
ptbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
addgasestimateratio = 0.3
proxyport = 10304

[[multichain]]
chainID = 57
name = "Syscoin"
gateway = "https://rpc.syscoin.org"
blkinterval = 60
blkdelay = 1
maxblkdelta = 10000
forwardblkdelay = 10
cbridge = "0x841ce48f9446c8e281d3f1444cb859b4a6d0738c"
otvault = "0x1E6b1ceAF75936f153ABB7B65FBa57AbaE14e6CE"
ptbridge = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
addgasestimateratio = 0.3

[[multichain]]
chainID = 336
name = "ShidenNetworkMainnet"
gateway = "https://evm.shiden.astar.network"
blkinterval = 20
blkdelay = 6
maxblkdelta = 300
forwardblkdelay = 100
cbridge = "0x841ce48F9446C8E281D3F1444cB859b4A6D0738C"
otvault = "0xBB7684Cc5408F4DD0921E5c2Cadd547b8f1AD573"
addgasestimateratio = 0.3
proxyport = 10305
