[executor]
# these contract info filters tells the executor for messages initiated from which contracts 
# it should submit the execution on-chain. basically these are the message passing app contracts 
# (the ones that implements MessageSenderApp/MessageReceiverApp) you deploy on source/destination chains
[[executor.contracts]]
chainid = 5
address = "<your application contract address>"
[[executor.contracts]]
chainid = 97
address = "<your application contract address>"

[sgnd]
# all read queries are executed through sgn node 0 grpc
sgn_grpc = "35.165.81.166:9090"
# all writes to sgn (sending transactions) are delegated through sgn gateway for now so you don't
# need to have a sgn account key
gateway_grpc = "35.165.81.166:20000"

[eth]
# the location of your eth keystore. it is used for submitting execution on-chain
signer_keystore = "/home/ubuntu/.executor/eth-ks/signer.json"
# don't forget to populate the passphrase of your keystore
signer_passphrase = "<your keystore passphrase>"

[db]
url = "localhost:26257"
