[executor]
# these contract info filters tells the executor for messages initiated from which contracts 
# it should submit the execution on-chain. basically these are the message passing app contracts 
# (the ones that implements MessageSenderApp/MessageReceiverApp) you deploy on source/destination chains
[[executor.contracts]]
chainid = 5
address = "<your application contract address>"
[[executor.contracts]]
chainid = 97
address = "<your application contract address>"

[sgnd]
gateway = "https://cbridge-v2-test.celer.network"

[eth]
# the location of your eth keystore. it is used for submitting execution on-chain
signer_keystore = "/home/ubuntu/.executor/eth-ks/signer.json"
# don't forget to populate the passphrase of your keystore
# signer_passphrase = ""

[db]
url = "localhost:26257"
