[executor]
[[executor.contracts]]
chainid = 5
address = "<your application contract address>"
[[executor.contracts]]
chainid = 97
address = "<your application contract address>"

[sgnd]
gateway = "https://cbridge-v2-test.celer.network"

[eth]
signer_keystore = "/home/ubuntu/.executor/eth-ks/signer.json"
# signer_passphrase = ""

[db]
url = "localhost:26257"
